import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.tsx'

// Service worker: production only (dev keeps the live shell). Registration
// module is auto-generated by vite-plugin-pwa (injectManifest + autoUpdate):
// update found → in-SW skipWaiting takes over → page reloads to fresh build.
//
// Update discovery: the browser only revalidates sw.js on navigation, so a
// PWA resumed from memory would stay stale until force-restart. Re-check on
// foreground (before any interaction — under autoUpdate discovery == reload,
// so this never interrupts a session) and on reconnect. No hourly interval:
// sessions here are minutes-long; foregrounding covers every realistic stale
// case. Throttled so app-switcher spam doesn't revalidate constantly.
const MIN_SW_CHECK_GAP_MS = 10 * 60 * 1000;
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  let lastSwCheck = 0;
  const checkForSwUpdate = (reg: ServiceWorkerRegistration | undefined) => {
    if (!reg || reg.installing) return;
    if ('connection' in navigator && !navigator.onLine) return;
    const now = Date.now();
    if (now - lastSwCheck < MIN_SW_CHECK_GAP_MS) return;
    lastSwCheck = now;
    reg.update().catch(() => {});
  };
  registerSW({
    immediate: false,
    onRegisteredSW(_swUrl, reg) {
      if (!reg) return;
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') checkForSwUpdate(reg);
      });
      window.addEventListener('online', () => checkForSwUpdate(reg));
    },
  });
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
