import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.tsx'

// Service worker: production only (dev keeps the live shell). Registration
// module is auto-generated by vite-plugin-pwa (injectManifest + autoUpdate):
// update found → in-SW skipWaiting takes over → page reloads to fresh build.
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  registerSW({ immediate: false });
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
